2017-07-07 10:14:19,322 [Dummy-1:140597802792704] [django.db.backends:91] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2017-07-07 10:14:19,324 [Dummy-1:140597802792704] [django.db.backends:91] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2017-07-07 10:14:24,121 [Thread-2:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable 'tasklist' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [tasklist] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6ab3d500>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6b3a6938>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab31f50>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6b616b10>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6b632cf8>, \'status\': \'currenttask\', \'pausing_count\': 0, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6b632cb0>, \'running_count\': 0, \'stopping_count\': 30}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n\\n\\n<!--<div class="box">-\'>, <Variable Node: running_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: pausing_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: stopping_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: error_count>, <TextNode: u\'</span>\\n            </div\'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n            </ul>\\n     \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n\\n\\n                  <di\'>, <For Node: for task in tasklist, tail_len: 11>, <TextNode: u\'\\n\\t\\t\\t                \\n  \\t\\t\'>, <For Node: for i in p.p_content, tail_len: 33>, <TextNode: u\'\\n                        \'>, <Variable Node: p.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab96f50>, <TextNode: u\'?page=\'>, <Variable Node: p.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab9d150>, <TextNode: u\'?page=1">\\u9996\\u9875</a></li>\\n    \'>, <For Node: for i in p.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab9d7d0>, <TextNode: u\'?page=\'>, <Variable Node: p.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab9d9d0>, <TextNode: u\'?page=\'>, <Variable Node: p.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n              <!--<div c\'>, <For Node: for i in p2.p_content, tail_len: 27>, <TextNode: u\'\\n                        \'>, <Variable Node: p2.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p2.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p2.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab2b910>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab2bad0>, <TextNode: u\'?page2=1">\\u9996\\u9875</a></li>\\n   \'>, <For Node: for i in p2.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab31190>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab31390>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>]>}, {}]'
2017-07-07 10:14:24,138 [Thread-2:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6ab3d500>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6b3a6938>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab31f50>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6b616b10>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6b632cf8>, \'status\': \'currenttask\', \'pausing_count\': 0, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6b632cb0>, \'running_count\': 0, \'stopping_count\': 30}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-07-07 10:14:24,139 [Thread-2:140597553411840] [django.server:124] [INFO]- "GET /crawlermanage/tasks/ HTTP/1.1" 200 32587
2017-07-07 10:14:29,529 [Thread-3:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable '0' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [0] in u'[]'
2017-07-07 10:14:29,536 [Thread-3:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable '0' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [0] in u'[]'
2017-07-07 10:14:29,542 [Thread-3:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable '0' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [0] in u'[]'
2017-07-07 10:14:29,548 [Thread-3:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable '0' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [0] in u'[]'
2017-07-07 10:14:29,554 [Thread-3:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable '0' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [0] in u'[]'
2017-07-07 10:14:29,610 [Thread-3:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6b3d59b0>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6b3d58c0>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab80d90>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab80390>, u\'request\': <WSGIRequest: GET \'/crawlermanage/ecommercedata/?taskid=5956482e9c1da939bc88ae69\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab92638>, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6b632fc8>, \'status\': \'goods\'}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-07-07 10:14:29,611 [Thread-3:140597553411840] [django.server:124] [INFO]- "GET /crawlermanage/ecommercedata/?taskid=5956482e9c1da939bc88ae69 HTTP/1.1" 200 21084
2017-07-07 10:14:35,147 [Thread-4:140597553411840] [django.server:124] [INFO]- "GET /static/bootstrap/css/bootstrap.min.css.map HTTP/1.1" 200 542194
2017-07-07 10:14:42,736 [Thread-5:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable '0' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [0] in u'[]'
2017-07-07 10:14:42,742 [Thread-5:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable '0' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [0] in u'[]'
2017-07-07 10:14:42,748 [Thread-5:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable '0' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [0] in u'[]'
2017-07-07 10:14:42,754 [Thread-5:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable '0' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [0] in u'[]'
2017-07-07 10:14:42,761 [Thread-5:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable '0' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [0] in u'[]'
2017-07-07 10:14:42,814 [Thread-5:140597553411840] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6ab3d500>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6aaf6f50>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab9d590>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab3f3d0>, u\'request\': <WSGIRequest: GET \'/crawlermanage/ecommercedata/?taskid=5956482e9c1da939bc88ae69\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab334d0>, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab0f830>, \'status\': \'goods\'}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-07-07 10:14:42,816 [Thread-5:140597553411840] [django.server:124] [INFO]- "GET /crawlermanage/ecommercedata/?taskid=5956482e9c1da939bc88ae69 HTTP/1.1" 200 21084
2017-07-07 10:14:46,426 [Thread-6:140597544232704] [django.template:925] [DEBUG]- Exception while resolving variable 'tasklist' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [tasklist] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6aaf6ed8>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6ab070c8>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab47490>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab80fd0>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab1ba28>, \'status\': \'currenttask\', \'pausing_count\': 0, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab1b128>, \'running_count\': 0, \'stopping_count\': 30}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n\\n\\n<!--<div class="box">-\'>, <Variable Node: running_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: pausing_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: stopping_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: error_count>, <TextNode: u\'</span>\\n            </div\'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n            </ul>\\n     \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n\\n\\n                  <di\'>, <For Node: for task in tasklist, tail_len: 11>, <TextNode: u\'\\n\\t\\t\\t                \\n  \\t\\t\'>, <For Node: for i in p.p_content, tail_len: 33>, <TextNode: u\'\\n                        \'>, <Variable Node: p.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab63990>, <TextNode: u\'?page=\'>, <Variable Node: p.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab63b50>, <TextNode: u\'?page=1">\\u9996\\u9875</a></li>\\n    \'>, <For Node: for i in p.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab6b050>, <TextNode: u\'?page=\'>, <Variable Node: p.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab6b1d0>, <TextNode: u\'?page=\'>, <Variable Node: p.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n              <!--<div c\'>, <For Node: for i in p2.p_content, tail_len: 27>, <TextNode: u\'\\n                        \'>, <Variable Node: p2.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p2.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p2.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab68290>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab68450>, <TextNode: u\'?page2=1">\\u9996\\u9875</a></li>\\n   \'>, <For Node: for i in p2.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab68a50>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab68c10>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>]>}, {}]'
2017-07-07 10:14:46,441 [Thread-6:140597544232704] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6aaf6ed8>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6ab070c8>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab47490>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab80fd0>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab1ba28>, \'status\': \'currenttask\', \'pausing_count\': 0, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab1b128>, \'running_count\': 0, \'stopping_count\': 30}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-07-07 10:14:46,443 [Thread-6:140597544232704] [django.server:124] [INFO]- "GET /crawlermanage/tasks/ HTTP/1.1" 200 32587
2017-07-07 10:14:51,953 [Thread-7:140597535840000] [django.template:925] [DEBUG]- Exception while resolving variable 'tasklist' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [tasklist] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6ab07410>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6aaf6c08>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6b616a10>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab80ad0>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/?page2=3\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6b645ea8>, \'status\': \'historytask\', \'pausing_count\': 0, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab89f38>, \'running_count\': 0, \'stopping_count\': 30}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n\\n\\n<!--<div class="box">-\'>, <Variable Node: running_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: pausing_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: stopping_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: error_count>, <TextNode: u\'</span>\\n            </div\'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n            </ul>\\n     \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n\\n\\n                  <di\'>, <For Node: for task in tasklist, tail_len: 11>, <TextNode: u\'\\n\\t\\t\\t                \\n  \\t\\t\'>, <For Node: for i in p.p_content, tail_len: 33>, <TextNode: u\'\\n                        \'>, <Variable Node: p.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab2b050>, <TextNode: u\'?page=\'>, <Variable Node: p.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab3f390>, <TextNode: u\'?page=1">\\u9996\\u9875</a></li>\\n    \'>, <For Node: for i in p.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab475d0>, <TextNode: u\'?page=\'>, <Variable Node: p.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab47750>, <TextNode: u\'?page=\'>, <Variable Node: p.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n              <!--<div c\'>, <For Node: for i in p2.p_content, tail_len: 27>, <TextNode: u\'\\n                        \'>, <Variable Node: p2.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p2.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p2.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab8eb10>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab8ecd0>, <TextNode: u\'?page2=1">\\u9996\\u9875</a></li>\\n   \'>, <For Node: for i in p2.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fdf6aba1310>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fdf6aba14d0>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>]>}, {}]'
2017-07-07 10:14:51,967 [Thread-7:140597535840000] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6ab07410>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6aaf6c08>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6b616a10>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab80ad0>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/?page2=3\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6b645ea8>, \'status\': \'historytask\', \'pausing_count\': 0, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab89f38>, \'running_count\': 0, \'stopping_count\': 30}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-07-07 10:14:51,968 [Thread-7:140597535840000] [django.server:124] [INFO]- "GET /crawlermanage/tasks/?page2=3 HTTP/1.1" 200 32565
2017-07-07 10:14:55,097 [Thread-10:140597519054592] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6aaf6ed8>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6b3d56e0>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab9b790>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6b3bcb50>, u\'request\': <WSGIRequest: GET \'/crawlermanage/ecommercedata/?taskid=595ee4869c1da90d492588e2\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6b63d488>, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6b63d6c8>, \'status\': \'goods\'}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-07-07 10:14:55,098 [Thread-10:140597519054592] [django.server:124] [INFO]- "GET /crawlermanage/ecommercedata/?taskid=595ee4869c1da90d492588e2 HTTP/1.1" 200 36078
2017-07-07 10:16:01,267 [Thread-11:140597519054592] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/ecommercedata.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6ab07320>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6b3a6938>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab6bdd0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab6b290>, u\'request\': <WSGIRequest: GET \'/crawlermanage/ecommercedata/?taskid=595ee4869c1da90d492588e2\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab09ab8>, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab099e0>, \'status\': \'goods\'}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-07-07 10:16:01,269 [Thread-11:140597519054592] [django.server:124] [INFO]- "GET /crawlermanage/ecommercedata/?taskid=595ee4869c1da90d492588e2 HTTP/1.1" 200 35236
2017-07-07 10:16:25,551 [Thread-12:140597519054592] [django.template:925] [DEBUG]- Exception while resolving variable 'tasklist' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [tasklist] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6ab07848>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6ab072a8>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab06f10>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab06390>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab33710>, \'status\': \'currenttask\', \'pausing_count\': 0, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab33680>, \'running_count\': 0, \'stopping_count\': 30}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n\\n\\n<!--<div class="box">-\'>, <Variable Node: running_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: pausing_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: stopping_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: error_count>, <TextNode: u\'</span>\\n            </div\'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n            </ul>\\n     \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n\\n\\n                  <di\'>, <For Node: for task in tasklist, tail_len: 11>, <TextNode: u\'\\n\\t\\t\\t                \\n  \\t\\t\'>, <For Node: for i in p.p_content, tail_len: 33>, <TextNode: u\'\\n                        \'>, <Variable Node: p.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fdf6b616a90>, <TextNode: u\'?page=\'>, <Variable Node: p.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fdf6b616890>, <TextNode: u\'?page=1">\\u9996\\u9875</a></li>\\n    \'>, <For Node: for i in p.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab1e510>, <TextNode: u\'?page=\'>, <Variable Node: p.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab1e6d0>, <TextNode: u\'?page=\'>, <Variable Node: p.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n              <!--<div c\'>, <For Node: for i in p2.p_content, tail_len: 27>, <TextNode: u\'\\n                        \'>, <Variable Node: p2.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p2.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p2.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab78590>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab78750>, <TextNode: u\'?page2=1">\\u9996\\u9875</a></li>\\n   \'>, <For Node: for i in p2.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab78d50>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fdf6ab78f10>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>]>}, {}]'
2017-07-07 10:16:25,568 [Thread-12:140597519054592] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6ab07848>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6ab072a8>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab06f10>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab06390>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab33710>, \'status\': \'currenttask\', \'pausing_count\': 0, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab33680>, \'running_count\': 0, \'stopping_count\': 30}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-07-07 10:16:25,570 [Thread-12:140597519054592] [django.server:124] [INFO]- "GET /crawlermanage/tasks/ HTTP/1.1" 200 32587
2017-07-07 10:16:27,448 [Thread-13:140597519054592] [django.template:925] [DEBUG]- Exception while resolving variable 'error1' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error1] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fdf68aabdd0>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-07-07 10:16:27,468 [Thread-13:140597519054592] [django.template:925] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fdf68aabdd0>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-07-07 10:16:27,469 [Thread-13:140597519054592] [django.template:925] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fdf68aabdd0>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-07-07 10:16:27,470 [Thread-13:140597519054592] [django.template:925] [DEBUG]- Exception while resolving variable 'error2' in template 'crawlermanage/layout.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error2] in u'[{\'False\': False, \'None\': None, \'True\': True}, {\'ips\': [<Machine: Machine object>, <Machine: Machine object>, <Machine: Machine object>]}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n<div class="box box-prim\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7fdf68aabdd0>, <TextNode: u\'-->\\n              <!-- te\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <Variable Node: error2>, <TextNode: u\'</p>\\n              </div>\'>, <IfNode>, <TextNode: u\' -->\\n              </div>\'>, <For Node: for i in ips, tail_len: 5>, <TextNode: u\'\\n                        \'>]>}]'
2017-07-07 10:16:27,476 [Thread-13:140597519054592] [django.server:124] [INFO]- "GET /crawlermanage/layout/ HTTP/1.1" 200 16605
2017-07-07 10:16:28,197 [Thread-14:140597519054592] [django.server:124] [INFO]- "GET /crawlermanage/machinelist/ HTTP/1.1" 200 11081
2017-07-07 10:16:28,912 [Thread-15:140597519054592] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/process_list.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6ab8a410>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6ab8a2a8>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab1d2d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab1d6d0>, u\'request\': <WSGIRequest: GET \'/crawlermanage/processlist/\'>}, {}, {\'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab24440>, \'pc_name\': []}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-07-07 10:16:28,913 [Thread-15:140597519054592] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/process_list.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6ab8a410>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6ab8a2a8>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab1d2d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab1d6d0>, u\'request\': <WSGIRequest: GET \'/crawlermanage/processlist/\'>}, {}, {\'p\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab24440>, \'pc_name\': []}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-07-07 10:16:28,914 [Thread-15:140597519054592] [django.server:124] [INFO]- "GET /crawlermanage/processlist/ HTTP/1.1" 200 11951
2017-07-07 10:16:38,143 [Thread-16:140597519054592] [django.template:925] [DEBUG]- Exception while resolving variable 'tasklist' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [tasklist] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6ab8a938>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6ab8a320>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab9b0d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab9b510>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab2fc20>, \'status\': \'currenttask\', \'pausing_count\': 0, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf7b9a0b48>, \'running_count\': 0, \'stopping_count\': 30}, {\'block\': <Block Node: maincontent. Contents: [<TextNode: u\'\\n\\n\\n<!--<div class="box">-\'>, <Variable Node: running_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: pausing_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: stopping_count>, <TextNode: u\'</span>\\n            </div\'>, <Variable Node: error_count>, <TextNode: u\'</span>\\n            </div\'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n            </ul>\\n     \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n\\n\\n\\n                  <di\'>, <For Node: for task in tasklist, tail_len: 11>, <TextNode: u\'\\n\\t\\t\\t                \\n  \\t\\t\'>, <For Node: for i in p.p_content, tail_len: 33>, <TextNode: u\'\\n                        \'>, <Variable Node: p.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fdf68ab0b50>, <TextNode: u\'?page=\'>, <Variable Node: p.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fdf68ab0550>, <TextNode: u\'?page=1">\\u9996\\u9875</a></li>\\n    \'>, <For Node: for i in p.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fdf68ab0f10>, <TextNode: u\'?page=\'>, <Variable Node: p.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fdf68aad110>, <TextNode: u\'?page=\'>, <Variable Node: p.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>, <IfEqualNode>, <TextNode: u\'\\n                \'>, <IfEqualNode>, <TextNode: u\'\\n              <!--<div c\'>, <For Node: for i in p2.p_content, tail_len: 27>, <TextNode: u\'\\n                        \'>, <Variable Node: p2.p_count>, <TextNode: u\'</span> \\u6761\\u8bb0\\u5f55\\uff0c\\u603b <span  clas\'>, <Variable Node: p2.p_pages>, <TextNode: u\'</span> \\u9875\\uff0c\\u5f53\\u524d\\u5728<span class=\'>, <Variable Node: p2.page>, <TextNode: u\'</span>\\u9875\\n                \'>, <django.template.defaulttags.URLNode object at 0x7fdf68aa6f90>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_previous>, <TextNode: u\'">&laquo;</a></li>\\n      \'>, <django.template.defaulttags.URLNode object at 0x7fdf68ac2190>, <TextNode: u\'?page2=1">\\u9996\\u9875</a></li>\\n   \'>, <For Node: for i in p2.p_range, tail_len: 9>, <TextNode: u\'\\n                        \'>, <django.template.defaulttags.URLNode object at 0x7fdf68ac2790>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_pages>, <TextNode: u\'">\\u5c3e\\u9875</a></li>\\n           \'>, <django.template.defaulttags.URLNode object at 0x7fdf68ac2950>, <TextNode: u\'?page2=\'>, <Variable Node: p2.p_next>, <TextNode: u\'">&raquo;</a></li>\\n      \'>]>}, {}]'
2017-07-07 10:16:38,164 [Thread-16:140597519054592] [django.template:925] [DEBUG]- Exception while resolving variable 'page' in template 'crawlermanage/tasks.html'.
Traceback (most recent call last):
  File "/home/haomao/pythonVir/mainenv/local/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [page] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7fdf6ab8a938>>, \'user\': <SimpleLazyObject: <function <lambda> at 0x7fdf6ab8a320>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7fdf6ab9b0d0>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7fdf6ab9b510>, u\'request\': <WSGIRequest: GET \'/crawlermanage/tasks/\'>}, {}, {\'p2\': <crawlermanage.utils.page.paging instance at 0x7fdf6ab2fc20>, \'status\': \'currenttask\', \'pausing_count\': 0, \'error_count\': 0, \'p\': <crawlermanage.utils.page.paging instance at 0x7fdf7b9a0b48>, \'running_count\': 0, \'stopping_count\': 30}, {\'block\': <Block Node: script. Contents: [<TextNode: u\'\\n<script src="../../stati\'>, <Variable Node: page>, <TextNode: u\'"\\n                  if(pa\'>]>}]'
2017-07-07 10:16:38,165 [Thread-16:140597519054592] [django.server:124] [INFO]- "GET /crawlermanage/tasks/ HTTP/1.1" 200 32587
